/* Generated by Yosys 0.6+56 (git sha1 01a5f71, gcc 4.8.4-2ubuntu1~14.04.1 -fPIC -Os) */

module ff_mult16appx(clk, aa, bb, yy1, yy2, yy3);
  wire [31:0] _0_;
  wire [31:0] _1_;
  reg [15:0] a1;
  input [15:0] aa;
  reg [15:0] b1;
  input [15:0] bb;
  input clk;
  wire [31:0] y3;
  output [31:0] yy1;
  reg [31:0] yy1;
  output [31:0] yy2;
  output [31:0] yy3;
  reg [31:0] yy3;
  assign _0_ = yy2 + y3;
  assign _1_ = y3[15:0] * b1;
  assign yy2 = _1_ * a1;
  always @(posedge clk)
      yy1 <= _0_;
  always @(posedge clk)
      yy3 <= y3;
  always @(posedge clk)
      a1 <= aa;
  always @(posedge clk)
      b1 <= bb;
  mult16exact m16xct (
    .a(a1),
    .b(b1),
    .y(y3)
  );
endmodule

module mult16exact(a, b, y);
  input [15:0] a;
  input [15:0] b;
  output [31:0] y;
  assign y = a * b;
endmodule
